### PR TITLE
Some changes in translation

### PR DESCRIPTION
**Pull request by kvsmirnov**
Corrected and updated Russian translation
Added some not translated strings
Merged lines with difference in punctuation or letter case (spam and
Spam, MB and Mb for example)

### CODE REVIEW

**Comment by rimas-kudelis** [comment]
I'm not sure if it's worthwhile to make string changes in this old codebase. @Udera what do you think?

**Comment by Udera** [comment]
We asked for some updates: https://github.com/vexim/vexim2/issues/191
But we do need to touch all the other translation files as well?

There are different writings of `e-mail` `email` `mail` ...

**Comment by rimas-kudelis** [comment]
@kvsmirnov please don't put all your fixes and changes in one PR, it will only make it less likely to be accepted. The smaller the updates, the better.

Particularly, I don't think we should accept your changes which add backticks to SQL queries, because that makes them totally incompatible with PostgreSQL. Don't forget we're using PDO – a DB abstraction layer which should be taking care of adding them when using MySQL.

**Comment by kvsmirnov** [comment]
I have MySQL 8 on my FreeBSD servers. MySQL 8 does not accept queries without backticks... Sorry, I have not tested this with PostgreSQL. I will stop using vexim2 in some weeks. My team writing own interface

**Comment by rimas-kudelis** [comment]
I'll say it differently: were you fixing the backticks preemtively, or were you actually affected by the bug? Like I said, PDO is an abstraction layer, so expect it to be adding backticks automatically when querying MySQL.

**Comment by kvsmirnov** [comment]
https://dev.mysql.com/doc/refman/8.0/en/keywords.html

**Comment by kvsmirnov** [comment]
I have MySQL 8.0.0, Apache 2.4, PHP 7.1 at my servers

**Pull request closed without merging**
