### PR TITLE
Update db schemas

### PR DESCRIPTION
**Pull request by rimas-kudelis**
Some late changes to the `users` table:

- column `forward`: changed from `VARCHAR(255)` to `VARCHAR(4096)` (as requested by @runout-at)
- column `unseen`: added a `NOT NULL` constraint
- column `vacation`: changed from `VARCHAR(1024)` to `TEXT`

This should be applied after #187, the diff will be much smaller then. :)

### CODE REVIEW

**Comment by Udera** [comment]
If we restrict the column `unseen`, we should check the scripts if they handle this restriction correctly (adminuser..., userchange...).

**Comment by rimas-kudelis** [comment]
Isn't it processed in the same way as other columns?

**Comment by rimas-kudelis** [comment]
I just checked my setup, and there are no rows matching the `unseen IS NULL` criteria.
I also grepped our sources for this word, and wherever we touch this field, we always set it to either 1 or 0, never NULL. I don't think this change to `unseen` is dangerous.

**Comment by Udera** [comment]
The only dangerous fields are optional fields that can be disabled for a domain (sa, antivirus, pipe, ...). `unseen` is always an option, so it shouldn't matter.

**Comment by Udera** [comment]
This branch has conflicts, can you rebase?

**Comment by rimas-kudelis** [comment]
Can we resolve #187 first?

**Comment by rimas-kudelis** [comment]
Or do you want to merge in this one first, and then go to #187? Either way suits me, I just have to know what to rebase on what. :)

**Comment by Udera** [comment]
Let's do #187 first.

**Comment by rimas-kudelis** [comment]
PR updated.

**Pull request merged**
