### PR TITLE
Fixing issue #138

### PR DESCRIPTION
**Pull request by Udera**
Fixing https://github.com/vexim/vexim2/issues/138

### CODE REVIEW

**Comment by rimas-kudelis** [comment]
Won't this fail miserably if the HELO identifier is not numeric, just like you reported in #138?

**Comment by Udera** [comment]
yes, that's not working either

**Comment by Udera** [comment]
Could we just use `match` instead of `matchip`?

**Comment by Udera** [comment]
I changed the HELO-ACLs to check these conditions:

- raw IP addresses are not RFC compliant (must be inside [])
- IP address and hostname from server is not allowed as HELO-name

I didn't add further checks like:

- check for an IP part like in `134-24-233-13.dynamic-range.example` because this could block legitimate users, dynamic-ips are as well checked by spamassassin)
- HELO contains my domains or subdomains. You perhaps use your own domain for some hosts which want to send mails and are not part of the relay hosts.
- some more checks on the syntax (single word, point at the end, ...)

However, we could keep some more rules in that are commented by default.

**Comment by Udera** [comment]
Seems to work as it should:
````
2016-07-21 14:29:05 H=(192.168.0.91) [203.171.31.60] rejected EHLO or HELO 192.168.0.91: Access denied - Invalid HELO name (See RFC2821 4.1.3)
2016-07-21 14:39:50 H=(113.162.6.35) [113.162.6.35] rejected EHLO or HELO 113.162.6.35: Access denied - Invalid HELO name (See RFC2821 4.1.3)
2016-07-21 16:39:33 H=(144.76.86.27) [80.78.76.185] rejected EHLO or HELO 144.76.86.27: Access denied - Invalid HELO name (See RFC2821 4.1.3)
2016-07-21 17:51:24 H=rrcs-69-75-209-180.west.biz.rr.com (192.168.0.91) [69.75.209.180] rejected EHLO or HELO 192.168.0.91: Access denied - Invalid HELO name (See RFC2821 4.1.3)
````
The last line is a bit confusing at first. The sender actually used `192.168.0.91` and because I use rDNS, exim4 automatically resolved the hostname associated to `69.75.209.180` (real sender_ip).

In contrast a normal mail with properly configured hostname and DNS entry looks like:
````
2016-07-21 20:51:01 1bQKvq-00015q-Fz <= redacted@hotmail.fr H=bay004-omc2s20.hotmail.com [65.54.190.95] P=esmtps X=TLS1.2:ECDHE_RSA_AES_256_CBC_SHA384:256 S=                                                                                                11033 id=VI1PR04@VI1PR04MB1458.abc.outlook.com 
````

**Comment by Udera** [comment]
We are not changing the default behavior, this PR seems to be working....

**Pull request merged**
