### PR TITLE
Update translations. Fixes #191

### LINKED ISSUE #191: Update translation
Vexim2.3 brings a number of new strings. The existing translations and `vexim2/vexim/locale/template.pot` have to be reviewed.

### PR DESCRIPTION
**Pull request by rimas-kudelis**

### CODE REVIEW

**Comment by Udera** [comment]
A lot of translations still contain a wrong version, or do you want to update this string once the files were reviewed?
` "Project-Id-Version: template\n"`

**Comment by rimas-kudelis** [comment]
That string doesn't really matter, but I've just updated it.

**Comment by Udera** [comment]
Should we merge this and then ping all the initial translators?

**Comment by rimas-kudelis** [comment]
Yes, although I wouldn't hold back the release just because of translations.

**Comment by Udera** [comment]
Sure, I put 2.3.1 as milestone in #191.

**Pull request merged**
