### PR TITLE
Color disabled accounts/domains red

### PR DESCRIPTION
**Pull request by Udera**
Fixes https://github.com/vexim/vexim2/issues/86

### CODE REVIEW

**Comment by rimas-kudelis** [comment]
I'd go for gray, not red. ;) You don't disable things to make them more prominent, you disable because you no longer need them.

**Comment by Udera** [comment]
I thought more of a temporary state. If you really don't need the domain/account, you can also delete it. Red is perhaps too alerting, since it's not a real error/problem of the system.

**Comment by rimas-kudelis** [comment]
Yeah, I think red is way too prominent.

**Comment by Udera** [comment]
I used a dark grey (color: #666).

**Pull request merged**
