### PR TITLE
check if user is enabled

### PR DESCRIPTION
**Pull request by runout-at**

### CODE REVIEW

**Comment by runout-at** [comment]
#158

**Comment by Udera** [comment]
Makes sense to put this in the complete config-file (https://github.com/vexim/vexim2/blob/master/docs/configure) and the imap authentication (e.g. https://github.com/vexim/vexim2/blob/master/docs/clients/dovecot.txt) as well.

**Comment by runout-at** [comment]
for an sql example in dovecot i just added the file to the branch
https://github.com/runout-at/vexim2/blob/lmtp-for-dovecot/docs/clients/dovecot/dovecot-sql.conf.ext

**Comment by Udera** [comment]
Yes, but this is a little bug fix that can easily be tested and then merged for the vexim2.3-release.

**Comment by runout-at** [comment]
ok. done.

**Pull request merged**
