### PR TITLE
Domainguess left trim

### PR DESCRIPTION
**Pull request by runout-at**
enhancement of domainguess feature

solves #135

cut off string given in $domainguess_lefttrim from left side of hostname

### CODE REVIEW

**Comment by rimas-kudelis** [comment]
From my understanding, with this variable, the regex expands to something like this:
```
/^mail|vexim\./
```
right?
If so, then I think this is not correct, as it matches `^mail` or `vexim\.`. I think you should use braces. around the contents of `$domainguess_lefttrim` variable whne using it in the regex.

**Comment by runout-at** [comment]
ok. you are right. i will fix this.

**Comment by runout-at** [comment]
now it should expand to `/^(mail|vexim)\./`

**Comment by Udera** [comment]
I tested this PR:
mail.example.org -> @example.org
mailn.example.org -> @mailn.example.org
quarks.mail.example.org -> @quarks.mail.example.org

So it does what it should.

**Pull request merged**
